### ISSUE TITLE
Lambda Literal Not Working With SQL Connection

### ISSUE THREAD

**Issue by 7enderhead** [lotabout/axe#3]
```racket
#lang axe

(require db)

(define connection
  (virtual-connection
   (connection-pool
    (#(mysql-connect #:server "server"
                     #:user "user"
                     #:password "pwd"
                     #:database "db")))))
```

pkgs\axe\app.rkt:38:31: connection-pool: contract violation
  expected: a procedure
  given: (object:connection% ...)
  in: the 1st argument of
      (->*
       ((-> connection?))
       (#:max-connections
        (or/c (integer-in 1 10000) +inf.0)
        #:max-idle-connections
        (or/c (integer-in 1 10000) +inf.0))
       connection-pool?)
  contract from: <pkgs>/db-lib/db/base.rkt
  blaming: anonymous-module
   (assuming the contract is correct)
  at: <pkgs>/db-lib/db/base.rkt:240.2

**Comment by lotabout** [comment]
@7enderhead Could you please share the version of racket that you use?
Cannot reproduce in my local env with racket 6.8.

```
; tcp-connect: connection failed
;   detail: host not found
;   address: server
;   port number: 3306
;   step: 1
;   system error: nodename nor servname provided, or not known; errno=8
; [,bt for context]
```

**Comment by 7enderhead** [comment]
- Racket 6.10.1 on Windows 7
- of course, you would need a MySql database running somewhere to test the connection
- the given db data are just examples

**Comment by lotabout** [comment]
@7enderhead

```racket
(define connection
  (virtual-connection
   (connection-pool
;   ↓ The `#(..)` is a procedure and by `(#(..))`, you call this procedure right away
    (#(mysql-connect #:server "server"
                     #:user "user"
                     #:password "pwd"
                     #:database "db")))))
```

This should work
```racket
#lang axe

(require db)

(define connection
  (virtual-connection
   (connection-pool
    #(mysql-connect #:server "localhost"
                     #:user "root"
                     #:password "mollywang"
                     #:database "db"))))
```

**Comment by lotabout** [comment]
Close for now. Please reopen if there are still problems.

**Comment by 7enderhead** [comment]
- sorry, was really confused by the new syntax and how this was already the lambda's invocation...
